// Seed ingredients with real nutritional data (sourced from the original recipes repo)
// Values are per 100g

export const seedIngredients = [
  {
    name: 'pasta',
    category: 'cereal',
    calories: 359,
    protein: 12.5,
    carbs: 72.2,
    fat: 1.8,
    fiber: 3.2,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'arroz',
    category: 'cereal',
    calories: 364,
    protein: 6.7,
    carbs: 81.6,
    fat: 0.9,
    fiber: 1.4,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'pollo',
    category: 'proteina',
    calories: 167,
    protein: 20.0,
    carbs: 0,
    fat: 9.7,
    fiber: 0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'salmon',
    category: 'proteina',
    calories: 208,
    protein: 20.4,
    carbs: 0,
    fat: 13.4,
    fiber: 0,
    seasons: ['spring', 'autumn', 'winter'],
  },
  {
    name: 'huevo',
    category: 'proteina',
    calories: 155,
    protein: 12.6,
    carbs: 1.1,
    fat: 11.3,
    fiber: 0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'tomate',
    category: 'verdura',
    calories: 22,
    protein: 1.0,
    carbs: 3.5,
    fat: 0.1,
    fiber: 1.2,
    seasons: ['summer', 'autumn'],
  },
  {
    name: 'cebolla',
    category: 'verdura',
    calories: 33,
    protein: 1.2,
    carbs: 7.1,
    fat: 0.1,
    fiber: 1.4,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'ajo',
    category: 'verdura',
    calories: 119,
    protein: 4.3,
    carbs: 24.3,
    fat: 0.2,
    fiber: 1.2,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'aceite de oliva virgen',
    category: 'grasa',
    calories: 899,
    protein: 0,
    carbs: 0,
    fat: 99.9,
    fiber: 0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'patata',
    category: 'verdura',
    calories: 73,
    protein: 2.0,
    carbs: 15.4,
    fat: 0.1,
    fiber: 2.1,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'zanahoria',
    category: 'verdura',
    calories: 40,
    protein: 0.9,
    carbs: 7.3,
    fat: 0.2,
    fiber: 3.4,
    seasons: ['autumn', 'winter'],
  },
  {
    name: 'pimiento rojo',
    category: 'verdura',
    calories: 37,
    protein: 1.2,
    carbs: 6.4,
    fat: 0.4,
    fiber: 1.9,
    seasons: ['summer', 'autumn'],
  },
  {
    name: 'espinacas',
    category: 'verdura',
    calories: 31,
    protein: 3.6,
    carbs: 0.8,
    fat: 0.7,
    fiber: 2.6,
    seasons: ['spring', 'winter'],
  },
  {
    name: 'brocoli',
    category: 'verdura',
    calories: 36,
    protein: 4.4,
    carbs: 1.8,
    fat: 0.9,
    fiber: 2.6,
    seasons: ['autumn', 'winter'],
  },
  {
    name: 'calabacin',
    category: 'verdura',
    calories: 16,
    protein: 1.2,
    carbs: 1.8,
    fat: 0.2,
    fiber: 1.0,
    seasons: ['spring', 'summer'],
  },
  {
    name: 'lentejas',
    category: 'legumbre',
    calories: 304,
    protein: 23.8,
    carbs: 48.8,
    fat: 1.7,
    fiber: 17.0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'garbanzos',
    category: 'legumbre',
    calories: 341,
    protein: 20.4,
    carbs: 49.6,
    fat: 5.4,
    fiber: 15.5,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'leche entera',
    category: 'lacteo',
    calories: 63,
    protein: 3.1,
    carbs: 4.7,
    fat: 3.5,
    fiber: 0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'queso parmesano',
    category: 'lacteo',
    calories: 420,
    protein: 36.0,
    carbs: 0,
    fat: 29.7,
    fiber: 0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'pan integral',
    category: 'cereal',
    calories: 221,
    protein: 8.0,
    carbs: 41.2,
    fat: 2.5,
    fiber: 5.8,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'atun',
    category: 'proteina',
    calories: 130,
    protein: 29.0,
    carbs: 0,
    fat: 1.0,
    fiber: 0,
    seasons: ['spring', 'summer'],
  },
  {
    name: 'ternera',
    category: 'proteina',
    calories: 131,
    protein: 20.7,
    carbs: 0,
    fat: 5.4,
    fiber: 0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'coliflor',
    category: 'verdura',
    calories: 27,
    protein: 2.4,
    carbs: 2.4,
    fat: 0.3,
    fiber: 2.5,
    seasons: ['autumn', 'winter'],
  },
  {
    name: 'aguacate',
    category: 'fruta',
    calories: 141,
    protein: 1.5,
    carbs: 3.4,
    fat: 12.0,
    fiber: 5.3,
    seasons: ['autumn', 'winter'],
  },
  {
    name: 'platano',
    category: 'fruta',
    calories: 94,
    protein: 1.2,
    carbs: 21.1,
    fat: 0.3,
    fiber: 2.5,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'manzana',
    category: 'fruta',
    calories: 53,
    protein: 0.3,
    carbs: 12.4,
    fat: 0.4,
    fiber: 2.0,
    seasons: ['autumn', 'winter'],
  },
  {
    name: 'yogur natural',
    category: 'lacteo',
    calories: 57,
    protein: 3.3,
    carbs: 4.0,
    fat: 3.0,
    fiber: 0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'avena',
    category: 'cereal',
    calories: 375,
    protein: 11.7,
    carbs: 59.8,
    fat: 7.1,
    fiber: 10.1,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'mantequilla',
    category: 'grasa',
    calories: 750,
    protein: 0.6,
    carbs: 0.5,
    fat: 83.0,
    fiber: 0,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
  {
    name: 'harina de trigo',
    category: 'cereal',
    calories: 341,
    protein: 9.3,
    carbs: 70.6,
    fat: 1.2,
    fiber: 3.4,
    seasons: ['spring', 'summer', 'autumn', 'winter'],
  },
]
