// Seed recipes for the ONA catalog (authorId = null)
// ingredientNames will be resolved to IDs during seeding

export interface SeedRecipe {
  name: string
  imageUrl?: string
  prepTime: number
  meals: string[]
  seasons: string[]
  tags: string[]
  steps: string[]
  ingredients: Array<{ name: string; quantity: number; unit: string }>
}

export const seedRecipes: SeedRecipe[] = [
  // ── Recetas compartidas por usuarios ────────────────────────────────

  {
    name: 'Albondigas en salsa espanola',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Freir las albondigas en abundante aceite hasta dorar por todos lados, reservar en plato con papel absorbente',
      'Picar cebolla, zanahoria y ajo muy menudo, rehogar en cazuela con aceite colado de las albondigas',
      'Anadir sal, pimienta y harina, remover hasta disolver',
      'Verter el vino y un vaso de agua o caldo, cocinar 25 minutos a fuego lento removiendo',
      'Batir la salsa con batidora',
      'Verter en la cazuela, anadir las albondigas y cocer 10 minutos',
    ],
    ingredients: [
      { name: 'ternera', quantity: 1000, unit: 'g' },
      { name: 'cebolla', quantity: 200, unit: 'g' },
      { name: 'zanahoria', quantity: 150, unit: 'g' },
      { name: 'ajo', quantity: 10, unit: 'g' },
      { name: 'harina de trigo', quantity: 15, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 30, unit: 'g' },
    ],
  },
  {
    name: 'Falafel',
    prepTime: 35,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Precalentar horno a 200C',
      'Escurrir y secar bien los garbanzos',
      'Descongelar guisantes y exprimir el liquido',
      'Mezclar todos los ingredientes en procesador hasta obtener masa suave',
      'Dejar reposar 5-10 minutos, formar empanadas con las manos enharinadas',
      'Espolvorear con harina, pincelar con aceite y hornear 30 minutos, volteando a mitad',
    ],
    ingredients: [
      { name: 'garbanzos', quantity: 400, unit: 'g' },
      { name: 'guisantes', quantity: 150, unit: 'g' },
      { name: 'ajo', quantity: 6, unit: 'g' },
      { name: 'harina de trigo', quantity: 8, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 15, unit: 'g' },
    ],
  },
  {
    name: 'Ternera a la jardinera',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Dorar la carne a fuego fuerte',
      'Anadir ajo, cebolla y pimiento cortado pequeno, bajar fuego y cocer hasta que la cebolla este blanda',
      'Subir fuego y anadir vino',
      'Cuando evapore, echar tomate en taquitos y sofreir 5 minutos',
      'Anadir tomillo, caldo y zanahorias en rodajas, tapar 25 minutos a fuego bajo',
      'Anadir patata en taquitos, 20 minutos a fuego bajo',
      'Anadir guisantes y subir fuego, 5 minutos',
    ],
    ingredients: [
      { name: 'ternera', quantity: 250, unit: 'g' },
      { name: 'pimiento verde', quantity: 50, unit: 'g' },
      { name: 'cebolla', quantity: 80, unit: 'g' },
      { name: 'ajo', quantity: 3, unit: 'g' },
      { name: 'zanahoria', quantity: 150, unit: 'g' },
      { name: 'guisantes', quantity: 60, unit: 'g' },
      { name: 'tomate', quantity: 150, unit: 'g' },
      { name: 'patata', quantity: 150, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 20, unit: 'g' },
    ],
  },
  {
    name: 'Acelgas rehogadas',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Poner olla con agua y sal a hervir',
      'Separar pencas y hojas de las acelgas, lavar y trocear',
      'Pelar patatas y cortar en taquitos',
      'Cocer patatas 5 min, anadir pencas 5 min, anadir hojas 5 min, escurrir',
      'Dorar ajo en rodajas y cebolla picada en sarten con aceite',
      'Anadir las verduras escurridas con sal y pimenton, cocinar 2 minutos',
      'Bajar fuego y cocinar todo junto 5 minutos',
    ],
    ingredients: [
      { name: 'acelgas', quantity: 1000, unit: 'g' },
      { name: 'patata', quantity: 300, unit: 'g' },
      { name: 'ajo', quantity: 6, unit: 'g' },
      { name: 'cebolla', quantity: 100, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 15, unit: 'g' },
    ],
  },
  {
    name: 'Arroz al caldero',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [
      { name: 'arroz', quantity: 500, unit: 'g' },
      { name: 'ajo', quantity: 3, unit: 'g' },
    ],
  },
  {
    name: 'Crema de calabacin',
    prepTime: 0,
    meals: ['dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'easy', 'light', 'dinner'],
    steps: [
      'Trocear calabacines, cebolla y puerro, sofreir 10 minutos con aceite',
      'Anadir patata y caldo, cocer 20 minutos',
      'Triturar hasta obtener crema',
    ],
    ingredients: [
      { name: 'calabacin', quantity: 1000, unit: 'g' },
      { name: 'cebolla', quantity: 80, unit: 'g' },
      { name: 'puerro', quantity: 100, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 40, unit: 'ml' },
      { name: 'patata', quantity: 150, unit: 'g' },
    ],
  },
  {
    name: 'Carrilleras de ternera con vino tinto',
    prepTime: 0,
    meals: ['lunch'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'lunch'],
    steps: [],
    ingredients: [
      { name: 'ternera', quantity: 400, unit: 'g' },
      { name: 'cebolla', quantity: 200, unit: 'g' },
      { name: 'zanahoria', quantity: 150, unit: 'g' },
      { name: 'ajo', quantity: 6, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 100, unit: 'ml' },
    ],
  },
  {
    name: 'Cocido madrileno',
    prepTime: 0,
    meals: ['lunch'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'lunch', 'contundente'],
    steps: [
      'Poner los garbanzos en agua la noche anterior',
      'Poner a cocer toda la carne en olla grande, retirar espuma',
      'Cuando hierva, escurrir garbanzos y anadir a la olla',
      'Cocer 30 minutos en olla rapida',
      'En otra olla, cocer repollo, nabo y puerro 30 minutos',
      'Anadir patatas y zanahorias a la olla rapida hasta que esten tiernas',
      'Servir por separado: garbanzos con verduras, carnes y caldo',
    ],
    ingredients: [
      { name: 'garbanzos', quantity: 300, unit: 'g' },
      { name: 'ternera', quantity: 400, unit: 'g' },
      { name: 'pollo', quantity: 200, unit: 'g' },
      { name: 'patata', quantity: 300, unit: 'g' },
      { name: 'zanahoria', quantity: 150, unit: 'g' },
      { name: 'puerro', quantity: 100, unit: 'g' },
    ],
  },
  {
    name: 'Costillas a la riojana',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Dorar las costillas a fuego fuerte con aceite, reservar',
      'Pochar cebolla y ajo en laminas con sal',
      'Anadir pimiento y zanahoria picados, sofreir, anadir tomate y pimenton',
      'Anadir costillas y cubrir con agua, tapar y cocer 30 minutos',
      'Anadir patatas chascadas y cocer hasta que esten blandas',
    ],
    ingredients: [
      { name: 'patata', quantity: 400, unit: 'g' },
      { name: 'costillas', quantity: 1000, unit: 'g' },
      { name: 'cebolla', quantity: 100, unit: 'g' },
      { name: 'pimiento verde', quantity: 50, unit: 'g' },
      { name: 'pimiento rojo', quantity: 50, unit: 'g' },
      { name: 'tomate', quantity: 100, unit: 'g' },
      { name: 'ajo', quantity: 6, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 20, unit: 'g' },
    ],
  },
  {
    name: 'Curry de berenjena',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Precalentar horno a 200C, cortar berenjenas por la mitad, untar con aceite y sal, hornear 20 minutos',
      'Calentar aceite en olla, saltear cebolla 3-5 minutos',
      'Anadir ajo, comino, cilantro y canela, saltear 1 minuto',
      'Anadir pimiento, tomates, lentejas, albaricoques, sal, pimienta y berenjena asada',
      'Cocinar hasta que los pimientos esten tiernos',
      'Servir con arroz o naan',
    ],
    ingredients: [
      { name: 'berenjena', quantity: 400, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 5, unit: 'ml' },
      { name: 'cebolla', quantity: 100, unit: 'g' },
      { name: 'ajo', quantity: 10, unit: 'g' },
      { name: 'pimiento rojo', quantity: 80, unit: 'g' },
      { name: 'tomate', quantity: 400, unit: 'g' },
      { name: 'lentejas', quantity: 265, unit: 'g' },
    ],
  },
  {
    name: 'Judias verdes rehogadas',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Lavar, trocear judias y cortar patatas en dados, cocer en agua con sal hasta tiernas',
      'Escurrir bien, poner de nuevo en cazuela con poco aceite para absorber agua restante',
      'En sarten con aceite, pochar ajo en laminas, anadir pimenton a fuego muy bajo',
      'Verter contenido de la sarten sobre la verdura y mezclar',
    ],
    ingredients: [
      { name: 'judias verdes', quantity: 1000, unit: 'g' },
      { name: 'patata', quantity: 200, unit: 'g' },
      { name: 'ajo', quantity: 15, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 60, unit: 'g' },
    ],
  },
  {
    name: 'Menestra de verduras con carne',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Rehogar verduras con poco aceite 10 minutos: ajo y cebolla, luego pimiento, luego judia verde, alcachofas y guisantes',
      'Echar la carne cortada en taquitos',
      'Anadir vino blanco, 3 minutos',
      'Anadir un poco de agua, dejar reducir 20 minutos',
    ],
    ingredients: [
      { name: 'ajo', quantity: 10, unit: 'g' },
      { name: 'cebolla', quantity: 100, unit: 'g' },
      { name: 'pimiento rojo', quantity: 80, unit: 'g' },
      { name: 'guisantes', quantity: 100, unit: 'g' },
      { name: 'judias verdes', quantity: 150, unit: 'g' },
      { name: 'ternera', quantity: 200, unit: 'g' },
    ],
  },
  {
    name: 'Bacalao con tomate',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'dinner', 'lunch'],
    steps: [
      'Desalar el bacalao',
      'Poner el horno a calentar a tope',
      'Cocer el bacalao 5 minutos desde que vuelva a hervir',
      'Poner en bandeja de horno bien apretado',
      'Cubrir con salsa de tomate',
      'Cubrir con capa de mayonesa',
      'Dorar al horno',
    ],
    ingredients: [
      { name: 'bacalao', quantity: 300, unit: 'g' },
      { name: 'tomate', quantity: 200, unit: 'g' },
    ],
  },
  {
    name: 'Ceviche',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Poner el choclo 5 minutos en agua hirviendo, escurrir y enfriar',
      'Exprimir zumo de 4 limas',
      'Cortar pescado en tacos, salpimentar, anadir picante y zumo de lima, refrigerar 20-60 minutos',
      'En bol grande mezclar aguacate, mango, cebolla morada, tomate, choclo y cilantro en tacos',
      'Rociar con aceite y sal, mezclar con el pescado',
      'Decorar con lima y acompanar con nachos',
    ],
    ingredients: [
      { name: 'salmon', quantity: 300, unit: 'g' },
      { name: 'aguacate', quantity: 150, unit: 'g' },
      { name: 'cebolla', quantity: 80, unit: 'g' },
      { name: 'tomate', quantity: 100, unit: 'g' },
    ],
  },
  {
    name: 'Guisantes lagrima',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Poner agua abundante con sal a hervir',
      'Introducir guisantes, contar 5 minutos desde que hierva',
      'En sarten saltear ajo y cebolla cortada pequena',
      'Anadir taquitos de jamon',
      'Saltear guisantes 3 minutos',
    ],
    ingredients: [
      { name: 'guisantes', quantity: 300, unit: 'g' },
      { name: 'jamon', quantity: 50, unit: 'g' },
      { name: 'cebolla', quantity: 80, unit: 'g' },
      { name: 'ajo', quantity: 10, unit: 'g' },
    ],
  },
  {
    name: 'Lentejas guisadas',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [
      'Dejar lentejas en remojo 12 horas, retirar las que floten',
      'Picar cebolla, ajo, zanahoria, tomate y pimiento muy pequenos',
      'Sofreir cebolla y ajo 10 minutos',
      'Anadir pimiento, tomate, zanahoria y laurel, sofreir 2-3 minutos',
      'Anadir huesos y pimenton de la Vera',
      'Echar lentejas escurridas, remover 3 minutos',
      'Cubrir con agua fria, hervir y espumear',
      'A los 30 minutos anadir chorizo y morcilla, ajustar sal, cocer 30 minutos mas',
    ],
    ingredients: [
      { name: 'lentejas', quantity: 500, unit: 'g' },
      { name: 'zanahoria', quantity: 200, unit: 'g' },
      { name: 'ajo', quantity: 6, unit: 'g' },
      { name: 'cebolla', quantity: 200, unit: 'g' },
      { name: 'pimiento verde', quantity: 60, unit: 'g' },
      { name: 'tomate', quantity: 200, unit: 'g' },
      { name: 'aceite de oliva virgen', quantity: 40, unit: 'g' },
    ],
  },

  // ── Recetas compartidas (solo nombre/metadata) ──────────────────────

  {
    name: 'Lubina',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Espaguetti carbonara',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Cocido N',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Sushi en bowl',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Huevos al plato',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Arroz con conejo',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Fidegua gipsy',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Berenjenas con chermoula',
    imageUrl: '/images/recipes/berenjenas-con-chermoula.jpg',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Sandwich mixto',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Osobuco a la milanesa',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Pechuga pollo baja temperatura',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Lasana',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Salmon al horno con brocoli',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Crema zanahorias',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Crema de calabaza',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Pastela vegetariana Gipsy',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Pizza',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Muslos de pavo a la catalana',
    imageUrl: '/images/recipes/muslos-de-pavo-a-la-catalana.jpeg',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Pisto (Shakshuka)',
    imageUrl: '/images/recipes/pisto-shakshuka.jpg',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Aguachile de salmon',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'easy'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Ensalada thai de ternera',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Migas',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Arroz mexicano',
    imageUrl: '/images/recipes/arroz-mexicano.jpeg',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Paella de sepia y gambas',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Arroz al horno',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Tian de verduras',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Wok de ternera y verduras',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Cochinita pibil',
    imageUrl: '/images/recipes/cochinita-pibil.jpeg',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Pescado al horno',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Pollo al mole',
    imageUrl: '/images/recipes/pollo-al-mole.jpeg',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Romanescu',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Cinta de lomo con brocoli',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Tiradito de bacalao',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'easy'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Magret pekinesa',
    prepTime: 30,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'eventos'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Salteado de salmon',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'easy'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Tacos gipsy',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Quesadillas de sobrasada',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Arroz con bacalao',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Alitas de pollo',
    imageUrl: '/images/recipes/alitas-de-pollo.jpg',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Vichisoisse',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Dorada a la marsellesa',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Verduras estofadas',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Sopa Juliana',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Onigirazu Sandwich de sushi',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Espinacas a la crema',
    prepTime: 0,
    meals: ['dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'dinner', 'light'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Curry de patatas y guisantes',
    prepTime: 35,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Wrap de lechuga con noodles',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Berenjenas rellenas',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Fajitas de pollo',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'dinner', 'lunch'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Ramen',
    prepTime: 60,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Sopa Miso',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Vegan butter chicken',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Tzatziki',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Contramuslos de pollo guisados',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Tabule',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Berenjenas con queso',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Pollo agridulce gipsy',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Lasana de verduras',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Tajin de verduras y cordero',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'dinner', 'light', 'lunch'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Albondigas gipsy',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'easy'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Garbanzos con sobrasada',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Ensalada thai',
    prepTime: 0,
    meals: ['lunch', 'dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida'],
    steps: [],
    ingredients: [],
  },
  {
    name: 'Revuelto de espinacas y atun',
    prepTime: 0,
    meals: ['dinner'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    tags: ['compartida', 'dinner'],
    steps: [],
    ingredients: [],
  },
]
